---
title: "STOR 390 Final Paper"
author: "Sofia Zhang"
date: "2024-12-12"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(dplyr)
library(haven)

simulation = read_sas("~/Desktop/Final/sim.sas7bdat")
```

```{r}
occupations <- c(
  "management", "business_financial", "computer_mathematical", 
  "architecture_engineering", "life_physical_science", 
  "community_social_services", "legal", "education_training_library", 
  "arts_design_entertainment", "healthcare_practitioner", 
  "healthcare_support", "protective_service", 
  "food_preparation_serving", "building_maintenance", 
  "personal_care_service", "sales_related", 
  "office_admin_support", "farming_fishing_forestry", 
  "construction_extraction", "installation_maintenance", 
  "production", "transportation_material_moving", 
  "armed_forces"
)

for (i in 1:length(occupations)) {
  simulation[[occupations[i]]] <- ifelse(simulation$OCD392 == i, 1, 0)
}

simulation2 <- simulation %>% rename(stroke = MCQ160F, gender = RIAGENDR)
```

```{r}
simulation2$OCD392 <- NULL
simulation2$stroke[simulation2$stroke == 2] <- 0
```

```{r}
#Women
women<-simulation2 [simulation2 $gender==2,]
#Men
men<-simulation2 [simulation2 $gender==1,]
```

```{r}
library(LogicReg)
myanneal <- logreg.anneal.control(start = 2, end = -4, iter = 10000, update = 200)
```

```{r}
fitwomen_cat <- logreg(resp = women$stroke, bin=women[,c(seq(4,26))], type = 3,select = 1, ntrees = 2, nleaves=10, anneal.control = myanneal)

fitwomen_cat_all <- logreg(oldfit=fitwomen_cat,select=2,ntrees=c(1,3),nleaves=c(1,12),
 anneal.control=myanneal)

plot(fitwomen_cat_all)
```

```{r}
fitwomen_cat_a <- logreg(resp = women$stroke, bin=women[,c(seq(4,26))], type = 3, select= 1, ntrees = 3, nleaves=11,anneal.control = myanneal)
fitwomen_cat_a
plot(fitwomen_cat_a)
```

```{r}
fitwomen_cat_b <- logreg(resp = women$stroke, bin=women[,c(seq(4,26))], type = 3, select= 1, ntrees = 3, nleaves=11,anneal.control = myanneal)
fitwomen_cat_b
plot(fitwomen_cat_b)
```
```{r}
fitwomen_cat_c <- logreg(resp = women$stroke, bin=women[,c(seq(4,26))], type = 3, select= 1, ntrees = 3, nleaves=11,anneal.control = myanneal)
fitwomen_cat_c
plot(fitwomen_cat_c)
```

```{r}
fitwm_all_cv <- logreg(oldfit= fitwomen_cat,select=3,ntrees=c(1,3),nleaves=c(1,12),
 anneal.control=myanneal)
plot(fitwm_all_cv)

#Conclusion: Use have 10 predictors and 2 trees
```

```{r}
#pruned results
fitwomen_cat_a_2 <- logreg(resp = women$stroke, bin=women[,c(seq(4,26))], type = 3, select= 1, ntrees = 2, nleaves=10,anneal.control = myanneal)
fitwomen_cat_a_2
```

```{r}
par(cex = 0.6)
plot(fitwomen_cat_a_2,leaf.sz=2.0,leaf.txt.cx=0.7,full=TRUE)
```

```{r}
fitwomen_cat_b_2 <- logreg(resp = women$stroke, bin=women[,c(seq(4,26))], type = 3, select= 1, ntrees = 2, nleaves=10,anneal.control = myanneal)
fitwomen_cat_b_2
```

```{r}
par(cex = 0.6)
plot(fitwomen_cat_b_2,leaf.sz=2.2,leaf.txt.cx=0.7,full=TRUE,and.or.cx=0.9)
```

```{r}
fitwomen_cat_c_2 <- logreg(resp = women$stroke, bin=women[,c(seq(4,26))], type = 3, select= 1, ntrees = 2, nleaves=10,anneal.control = myanneal)
fitwomen_cat_c_2
plot(fitwomen_cat_c_2)
```

```{r}
par(cex = 0.6)
plot(fitwomen_cat_c_2,leaf.sz=2.2,leaf.txt.cx=0.8,full=TRUE,and.or.cx=0.8)
```

```{r}
women$L1_model3 <- 0
women$L1_model3[
  (women$protective_service == 1 | women$legal == 1) | 
  (women$installation_maintenance == 1 | women$armed_forces == 1) | 
  women$community_social_services == 1
] <- 1

women$L2_model3 <- 0
women$L2_model3[
  (women$office_admin_support == 1 | 
   (women$business_financial == 1 | women$food_preparation_serving == 1)) | 
  (women$education_training_library == 1 | women$personal_care_service == 1)
] <- 1

logistic_model3 <- glm(stroke ~ L1_model3 + L2_model3, data = women, family = "binomial")

summary(logistic_model3)
```
```{r}
logistic_model2 <- glm(stroke ~ women$protective_service + women$legal + women$community_social_services, 
                       data = women, family = "binomial")

summary(logistic_model2)
```

```{r}

```

