---
title: "Final Paper"
output:
  pdf_document: default
  html_document: default
date: "2024-12-13"
---

```{r}
library(dplyr)
library(haven)

simulation = read_sas("~/Desktop/Final/sim.sas7bdat")
```

```{r}
occupations <- c(
  "management", "business_financial", "computer_mathematical", 
  "architecture_engineering", "life_physical_science", 
  "community_social_services", "legal", "education_training_library", 
  "arts_design_entertainment", "healthcare_practitioner", 
  "healthcare_support", "protective_service", 
  "food_preparation_serving", "building_maintenance", 
  "personal_care_service", "sales_related", 
  "office_admin_support", "farming_fishing_forestry", 
  "construction_extraction", "installation_maintenance", 
  "production", "transportation_material_moving", 
  "armed_forces"
)

for (i in 1:length(occupations)) {
  simulation[[occupations[i]]] <- ifelse(simulation$OCD392 == i, 1, 0)
}

simulation2 <- simulation %>% rename(stroke = MCQ160F, gender = RIAGENDR)
```

```{r}
simulation2$OCD392 <- NULL
simulation2$stroke[simulation2$stroke == 2] <- 0
```

```{r}
#Women
women<-simulation2 [simulation2 $gender==2,]
#Men
men<-simulation2 [simulation2 $gender==1,]
```

```{r}
library(LogicReg)
myanneal <- logreg.anneal.control(start = 2, end = -4, iter = 10000, update = 200)
```

```{r}
fitmen_cat <- logreg(resp = men$stroke, bin=men[,c(seq(4,26))], type = 3,select = 1, ntrees = 2, nleaves=10, anneal.control = myanneal)

fitmen_cat_all <- logreg(oldfit=fitmen_cat,select=2,ntrees=c(1,3),nleaves=c(1,12),
 anneal.control=myanneal)

plot(fitmen_cat_all)
```
```{r}
fitm_all_cv <- logreg(oldfit= fitmen_cat,select=3,ntrees=c(1,3),nleaves=c(1,12),
 anneal.control=myanneal)
```

```{r}
plot(fitm_all_cv)

#11 predictors, 2 trees
```

```{r}
fitmen_cat_a_2 <- logreg(resp = men$stroke, bin=men[,c(seq(4,26))], type = 3, select= 1, ntrees = 2, nleaves=11,anneal.control = myanneal)
fitmen_cat_a_2
```

```{r}
par(cex = 0.6)
plot(fitmen_cat_a_2,leaf.sz=2.0,leaf.txt.cx=0.7,full=TRUE)
```

```{r}
fitmen_cat_b_2 <- logreg(resp = men$stroke, bin=men[,c(seq(4,26))], type = 3, select= 1, ntrees = 2, nleaves=11,anneal.control = myanneal)
fitmen_cat_b_2
```

```{r}
par(cex = 0.6)
plot(fitmen_cat_b_2,leaf.sz=2.2,leaf.txt.cx=0.6,full=TRUE)
```

```{r}
fitmen_cat_c_2 <- logreg(resp = men$stroke, bin=men[,c(seq(4,26))], type = 3, select= 1, ntrees = 2, nleaves=11,anneal.control = myanneal)
fitmen_cat_c_2
```
```{r}
par(cex = 0.6)
plot(fitmen_cat_c_2,leaf.sz=2.2,leaf.txt.cx=0.6,full=TRUE)
```
```{r}
# Define L1 and L2 for men dataset using Combination 3 logic
men$L1_model3 <- 0
men$L1_model3[
  ((men$food_preparation_serving == 0 & men$personal_care_service == 0) &
   men$education_training_library == 0) &
  (men$arts_design_entertainment == 0 & men$life_physical_science == 0)
] <- 1

men$L2_model3 <- 0
men$L2_model3[
  ((men$production == 1 | men$installation_maintenance == 1) |
   (men$armed_forces == 1 | men$architecture_engineering == 1)) |
  (men$legal == 1 | men$computer_mathematical == 1)
] <- 1

# Fit logistic regression model using L1 and L2
logistic_model3 <- glm(stroke ~ L1_model3 + L2_model3, data = men, family = "binomial")

# Display the summary of the model
summary(logistic_model3)
```
```{r}
logistic_model4 <- glm(stroke~ men$installation_maintenance +
                                 men$architecture_engineering +
                                 men$production +
                                 men$computer_mathematical, 
                       data = men, family = "binomial")
summary(logistic_model4)
```

